#include "token.h"

char *token_type_to_string(t_token_type token_type)
{
	switch (token_type) {
		case T_LEFT_PAREN:
			return strdup("T_LEFT_PAREN");
		case T_RIGHT_PAREN:
			return strdup("T_RIGHT_PAREN");
		case T_LEFT_BRACE:
			return strdup("T_LEFT_BRACE");
		case T_RIGHT_BRACE:
			return strdup("T_RIGHT_BRACE");
		case T_COMMA:
			return strdup("T_COMMA");
		case T_DOT:
			return strdup("T_DOT");
		case T_MINUS:
			return strdup("T_MINUS");
		case T_PLUS:
			return strdup("T_PLUS");
		case T_SEMICOLON:
			return strdup("T_SEMICOLON");
		case T_SLASH:
			return strdup("T_SLASH");
		case T_STAR:
			return strdup("T_STAR");
		case T_BANG:
			return strdup("T_BANG");
		case T_BANG_EQUAL:
			return strdup("T_BANG_EQUAL");
		case T_EQUAL:
			return strdup("T_EQUAL");
		case T_EQUAL_EQUAL:
			return strdup("T_EQUAL_EQUAL");
		case T_GREATER:
			return strdup("T_GREATER");
		case T_GREATER_EQUAL:
			return strdup("T_GREATER_EQUAL");
		case T_LESS:
			return strdup("T_LESS");
		case T_LESS_EQUAL:
			return strdup("T_LESS_EQUAL");
		case T_IDENTIFIER:
			return strdup("T_IDENTIFIER");
		case T_STRING:
			return strdup("T_STRING");
		case T_NUMBER:
			return strdup("T_NUMBER");
		case T_AND:
			return strdup("T_AND");
		case T_CLASS:
			return strdup("T_CLASS");
		case T_ELSE:
			return strdup("T_ELSE");
		case T_FALSE:
			return strdup("T_FALSE");
		case T_FUN:
			return strdup("T_FUN");
		case T_FOR:
			return strdup("T_FOR");
		case T_IF:
			return strdup("T_IF");
		case T_NIL:
			return strdup("T_NIL");
		case T_OR:
			return strdup("T_OR");
		case T_PRINT:
			return strdup("T_PRINT");
		case T_RETURN:
			return strdup("T_RETURN");
		case T_SUPER:
			return strdup("T_SUPER");
		case T_THIS:
			return strdup("T_THIS");
		case T_TRUE:
			return strdup("T_TRUE");
		case T_VAR:
			return strdup("T_VAR");
		case T_WHILE:
			return strdup("T_WHILE");
		case T_EOF:
			return strdup("T_EOF");
	}
	return (NULL);
}
